name=Boost.Variant
version=1.0.0
author=Boost Community
maintainer=Boost Community
sentence=Safe, generic, stack-based discriminated union container.
paragraph=Boost.Variant is part of the Boost C++ Libraries collection. It offers a simple solution for manipulating objects from a heterogeneous set of types in a uniform manner.
category=Data Structures
url=https://github.com/boostorg/variant
architectures=*
license=Boost Software License 1.0
